name: SpawnerVTGUI
version: 1.0
description: Provides a shop for VoteTokn
author: [nayoshi12,zLokkiN]
main: com.kyloka.voteTokenUI.main
commands:
  vtdebug:
    description: Debug command to test if your command works
    aliases: [votetokendebug,vtokendebug,votetdebug,vtdb,vtofkhazix]
  rng:
    description: hey
  balvote:
    description: a way to check your balance